### ISSUE TITLE
Updating master installs? 

### ISSUE THREAD

**Issue by foxnne** [tristanisham/zvm#12]
Hi! 

I've been using ZVM regularly for a while on both windows and macos, thanks for creating this! 

The only thing I've run into that is a small bother, is that I have to go into `.zvm` and delete the `master` folder before running `zvm i master` to install the latest version of master, otherwise it seems to stick on the already installed version. 

Am I missing some functionality to let me overwrite the installed master with a new version? 

Thanks!

**Comment by antlanc7** [comment]
I have the same issue. By the way, you can use `zvm rm master` to delete the previous version and then `zvm i master` to install the newer one.

**Comment by foxnne** [comment]
Ah thank you, that works!

**Comment by antlanc7** [comment]
This is just a workaround, I think it would be better to have the program overwrite completely the folder of the zig version in that case, 
Or maybe add a new command line option to choose the desired behavior.

**Comment by foxnne** [comment]
I agree. It would be pretty nice in my opinion to move old master versions to a subfolder in case rollback is needed, I'm often doing this currently. Or some way to handle multiple `master` versions until we hit 1.0.

**Comment by tristanisham** [comment]
@foxnne, that's a pretty good idea! Let me do some testing tonight to see what I can do.

**Comment by tristanisham** [comment]
So this bug was actually a pretty easy fix. Go's been updating it's file-checking API a bunch and the version ZVM used no longer worked as intended. I updated it and now the true master version should be installed. I do like the idea of adding previous versions so you can easily rollback in a future update.
This fix is coming out in v0.2.0
  ![zvm-master-bug-fix](https://github.com/tristanisham/zvm/assets/23124818/4441f4fd-5be5-4394-9cf1-95e95c9a43e7)

**Comment by foxnne** [comment]
Thanks!
