### ISSUE TITLE
Failed to open `zvm.tar`

### ISSUE THREAD

**Issue by matthew-dean** [tristanisham/zvm#17]
Curl command returns this:
```
tar: Error opening archive: Failed to open 'zvm.tar'
rm: zvm.tar: No such file or directory
```

**Comment by tristanisham** [comment]
What operating system and architecture are you running the install command on?

**Comment by matthew-dean** [comment]
@tristanisham macOS M1 Pro

**Comment by tristanisham** [comment]
Do you have the “tar” command installed on your system? 

Tristan Isham

On May 31, 2023, Tristan Isham ***@***.***> wrote:
> @tristanisham <https://github.com/tristanisham> macOS M1 Pro
>

—
Reply to this email directly, view it on GitHub
<https://github.com/tristanisham/zvm/issues/17#issuecomment-1571103939>,
or unsubscribe <https://github.com/notifications/unsubscribe-
auth/AFQNWURDUIVMCVV2KAIFZZ3XI7KI5ANCNFSM6AAAAAAYTCKXN4>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by dirkdev98** [comment]
In my case on a M1, wget was not installed. Resulting in the `zvm.tar` not being downloaded. The install script then still tries to extract it.

**Comment by tristanisham** [comment]
It should be fixed now. Without wget it'll fall back to Curl. Would you please double check? https://github.com/tristanisham/zvm/commit/2b8595c785076a2d478ee5d30cac58ea8dc7cb37

**Comment by dirkdev98** [comment]
It seems to not extract the downloaded tar now. https://github.com/tristanisham/zvm/pull/19 should fix that

**Comment by tristanisham** [comment]
Looks good to me! Thanks for the fix!

**Comment by matthew-dean** [comment]
Awesome, thanks! I'll try it out when I get the chance.
