### ISSUE TITLE
Please document about path

### ISSUE THREAD

**Issue by glyh** [tristanisham/zvm#22]
I don't find any relevant info, and I scan through the source code figuring out it should be at ~/.zvm/bin

**Comment by tristanisham** [comment]
Thanks for suggesting this! I sometimes forget what I know isn't what everyone else knows about the project. You should be happy with an upcoming release I'm planning on publishing today. It'll come with a new installer that will add ZVM to path by default and a self-updater to help make fixing bugs easier in the future. 

That being said, I'm updating the documentation too so that the path is extra clear.

**Comment by tristanisham** [comment]
@glyh Please check out the updated readme and let me know your thoughts? 

https://github.com/tristanisham/zvm#installing-zvm

**Comment by glyh** [comment]
Looks fine with me :)
