### ISSUE TITLE
"zvm i" goes through the entire install process even if there is no new version

### ISSUE THREAD

**Issue by lumenkeyes** [tristanisham/zvm#76]
(apologies for posting this as an empty issue initially, I don't use GH issues much and I misclicked)

**Is your feature request related to a problem? Please describe.**
Running "zvm i master" will reinstall the same version if no new version is available.

**Describe the solution you'd like**
Exit without doing anything if the latest version and the currently installed version are the same. I use the command to get the latest version, so it would be nice if there were a check to ensure that re-downloading + installing is actually necessary.

**Comment by VoilaNeighbor** [comment]
To make it worse, installation of ZLS is much slower than Zig itself on my host. I have to reinstall Zig before trying ZLS, just to see it timeout and getting killed...

**Comment by tristanisham** [comment]
ZLS is installed from a different source than Zig, and installing it really depends on both where you are and the reliability of the host. We've moved to installing ZLS from a new source since your comment @VoilaNeighbor so you may find the experience to be better. 

As for installing master ever time, that's a choice for right now, but I'd be willing to look at a pull request that adds this as the default with `--force` to install regardless of what's installed. It should also be a mode added to `settings.json`.

**Comment by VoilaNeighbor** [comment]
Thanks for your kind work here!

**Comment by tristanisham** [comment]
Merged and in production in ZVM v0.7.6
